sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lmarkes-evr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lmarkes-evr/docker-react npm run test